=== Antoniomp5/UD4_LMSGI/4/alumnos.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Alumnos (Alumno)>
<!ELEMENT Alumno (nombre, edad, nif, apto, observaciones, IP-MAC)>
<!ATTLIST Alumno id CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT edad(#PCDATA)>
<!ELEMENT nif (#PCDATA)>
<!ELEMENT apto (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT IP-MAC (#PCDATA)>

=== Antoniomp5/UD4_LMSGI/4/alumnos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libreria SYSTEM "alumnos.dtd">
<Alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="alumnos.xsd">
    <Alumno id="1">
        <nombre></nombre>
        <edad></edad>
        <nif></nif>
        <apto></apto>
        <observaciones></observaciones>
        <IP-MAC></IP-MAC>
    </Alumno>
</Alumnos>
