=== Antoniomp5/UD4_LMSGI/4/Clientes.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT clientes (cliente)>
<!ELEMENT sede (#PCDATA)>
<!ATTLIST sede id CDATA #REQUIRED>
<!ELEMENT empleado (#PCDATA)
<!ELEMENT fecha (#PCDATA)
<!ELEMENT cliente (#PCDATA)>
<!ATTLIST cliente id CDATA #REQUIRED>
<!ELEMENT vivienda (#PCDATA)>
<!ATTLIST vivienda id CDATA #REQUIRED>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT coste (#PCDATA)>
<!ELEMENT resumen (#PCDATA)>
<!ELEMENT plazo (#PCDATA)>

=== Antoniomp5/UD4_LMSGI/4/clientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libreria SYSTEM "Clientes.dtd">
<clientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="clientes.xsd">
    <sede id="1">
        <empleado></empleado>
        <fecha></fecha>
        <cliente></cliente>
        <vivienda>
            <descripcion></descripcion>
            <numero></numero>
        </vivienda>
        <coste></coste>
        <resumen></resumen>
        <plazo></plazo>
    </sede>
</clientes>

=== Antoniomp5/UD4_LMSGI/4/GestoriaClientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clientes SYSTEM "Clientes.dtd">
<clientes>
    <sede id="1">
        <empleado></empleado>
        <cliente codigo="">
            <fecha>Gabriel García Márquez</fecha>
            <descripcion>978-3-16-148410-0</descripcion>
            <numero>Novela</numero>
        </cliente>
        <vivienda id= "">
            <coste>Cien años de soledad</coste>
            <resumen>1967-06-05</resumen>
            <plazo>1967-06-05</plazo>
        </vivienda>
    </sede>

    <sede id="1">
        <empleado></empleado>
        <cliente codigo="">
            <fecha>Gabriel García Márquez</fecha>
            <descripcion>978-3-16-148410-0</descripcion>
            <numero>Novela</numero>
        </cliente>
        <vivienda id= "">
            <coste>Cien años de soledad</coste>
            <resumen>1967-06-05</resumen>
            <plazo>1967-06-05</plazo>
        </vivienda>
    </sede>


    <sede id="1">
        <empleado></empleado>
        <cliente codigo="">
            <fecha>Gabriel García Márquez</fecha>
            <descripcion>978-3-16-148410-0</descripcion>
            <numero>Novela</numero>
        </cliente>
        <vivienda id= "">
            <coste>Cien años de soledad</coste>
            <resumen>1967-06-05</resumen>
            <plazo>1967-06-05</plazo>
        </vivienda>
    </sede>


    <sede id="1">
        <empleado></empleado>
        <cliente codigo="">
            <fecha>Gabriel García Márquez</fecha>
            <descripcion>978-3-16-148410-0</descripcion>
            <numero>Novela</numero>
        </cliente>
        <vivienda id= "">
            <coste>Cien años de soledad</coste>
            <resumen>1967-06-05</resumen>
            <plazo>1967-06-05</plazo>
        </vivienda>
    </sede>


    <sede id="1">
        <empleado></empleado>
        <cliente codigo="">
            <fecha>Gabriel García Márquez</fecha>
            <descripcion>978-3-16-148410-0</descripcion>
            <numero>Novela</numero>
        </cliente>
        <vivienda id= "">
            <coste>Cien años de soledad</coste>
            <resumen>1967-06-05</resumen>
            <plazo>1967-06-05</plazo>
        </vivienda>
    </sede>

    <sede id="1">
        <empleado></empleado>
        <cliente codigo="">
            <fecha>Gabriel García Márquez</fecha>
            <descripcion>978-3-16-148410-0</descripcion>
            <numero>Novela</numero>
        </cliente>
        <vivienda id= "">
            <coste>Cien años de soledad</coste>
            <resumen>1967-06-05</resumen>
            <plazo>1967-06-05</plazo>
        </vivienda>
    </sede>


    <sede id="1">
        <empleado></empleado>
        <cliente codigo="">
            <fecha>Gabriel García Márquez</fecha>
            <descripcion>978-3-16-148410-0</descripcion>
            <numero>Novela</numero>
        </cliente>
        <vivienda id= "">
            <coste>Cien años de soledad</coste>
            <resumen>1967-06-05</resumen>
            <plazo>1967-06-05</plazo>
        </vivienda>
    </sede>


    <sede id="1">
        <empleado></empleado>
        <cliente codigo="">
            <fecha>Gabriel García Márquez</fecha>
            <descripcion>978-3-16-148410-0</descripcion>
            <numero>Novela</numero>
        </cliente>
        <vivienda id= "">
            <coste>Cien años de soledad</coste>
            <resumen>1967-06-05</resumen>
            <plazo>1967-06-05</plazo>
        </vivienda>
    </sede>

    <sede id="1">
        <empleado></empleado>
        <cliente codigo="">
            <fecha>Gabriel García Márquez</fecha>
            <descripcion>978-3-16-148410-0</descripcion>
            <numero>Novela</numero>
        </cliente>
        <vivienda id= "">
            <coste>Cien años de soledad</coste>
            <resumen>1967-06-05</resumen>
            <plazo>1967-06-05</plazo>
        </vivienda>
    </sede>


    <sede id="1">
        <empleado></empleado>
        <cliente codigo="">
            <fecha>Gabriel García Márquez</fecha>
            <descripcion>978-3-16-148410-0</descripcion>
            <numero>Novela</numero>
        </cliente>
        <vivienda id= "">
            <coste>Cien años de soledad</coste>
            <resumen>1967-06-05</resumen>
            <plazo>1967-06-05</plazo>
        </vivienda>
    </sede>

</clientes>
